### ISSUE TITLE
Why cpp_agrpc is faster than grpc_callback?

### ISSUE THREAD

**Issue by qicosmos** [npuichigo/agrpc#2]
Hi, as i know coroutine just change the style of async programming, don't improve performance, but i noticed your benchmark, the coroutine version is much faster than callback version on multiple cores server, why? What optimizations you did?

**Comment by npuichigo** [comment]
Do u mean recent callback apis for c++? The performance guide [here](https://grpc.io/docs/guides/performance/) shows that `
The callback API is easier to use than the completion-queue async API but is currently slower for truly high-QPS workloads. 

You can run the benchmark to see the QPS of cpp_grpc_callback (https://github.com/LesnyRumcajs/grpc_bench)

**Comment by npuichigo** [comment]
The performance with coroutine might be slightly better than cpp_grpc_mt since they can avoid the extra dynamic memory allocation for the OperationState and store it in the coroutine frame directly.

**Comment by qicosmos** [comment]
Thanks for your reply.
